import React, { useState, useEffect } from 'react';
import { api } from '../api/client';
import StatusBadge from '../components/StatusBadge';
import UrgencyBadge from '../components/UrgencyBadge';
import CategoryBadge from '../components/CategoryBadge';
import {
  ArrowLeft,
  RefreshCw,
  Copy,
  Check,
  User,
  Mail,
  Calendar,
  Sparkles,
  Bot,
  AlertCircle,
  MessageSquare,
  Clock,
  ShieldCheck,
} from 'lucide-react';

export default function RequestDetail({ ticketId, onBack }) {
  const [ticket, setTicket] = useState(null);
  const [loading, setLoading] = useState(true);
  const [regenerating, setRegenerating] = useState(false);
  const [updatingStatus, setUpdatingStatus] = useState(false);
  const [error, setError] = useState(null);
  const [copied, setCopied] = useState(false);
  const [successToast, setSuccessToast] = useState(null);

  const fetchTicketDetails = async () => {
    try {
      setLoading(true);
      setError(null);
      const data = await api.getRequestById(ticketId);
      setTicket(data);
    } catch (err) {
      console.error('Error fetching ticket details:', err);
      setError(err.message || 'Failed to load ticket details');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (ticketId) {
      fetchTicketDetails();
    }
  }, [ticketId]);

  const handleStatusChange = async (newStatus) => {
    if (!ticket || newStatus === ticket.status) return;

    try {
      setUpdatingStatus(true);
      const updated = await api.updateStatus(ticket.id, newStatus);
      setTicket(updated);
      showNotification(`Ticket status updated to "${newStatus}"`);
    } catch (err) {
      console.error('Failed to update status:', err);
      setError('Could not update ticket status: ' + err.message);
    } finally {
      setUpdatingStatus(false);
    }
  };

  const handleRegenerateReply = async () => {
    try {
      setRegenerating(true);
      setError(null);
      const updated = await api.regenerateReply(ticket.id);
      setTicket(updated);
      showNotification('AI Customer Support reply successfully regenerated by Gemini API!');
    } catch (err) {
      console.error('Failed to regenerate AI reply:', err);
      setError('Failed to regenerate AI reply: ' + err.message);
    } finally {
      setRegenerating(false);
    }
  };

  const handleCopyReply = () => {
    if (!ticket?.ai_reply) return;
    navigator.clipboard.writeText(ticket.ai_reply);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
    showNotification('AI response copied to clipboard!');
  };

  const showNotification = (msg) => {
    setSuccessToast(msg);
    setTimeout(() => setSuccessToast(null), 3500);
  };

  const formatDate = (dateStr) => {
    if (!dateStr) return '—';
    try {
      return new Date(dateStr).toLocaleString(undefined, {
        dateStyle: 'medium',
        timeStyle: 'short',
      });
    } catch {
      return dateStr;
    }
  };

  if (loading) {
    return (
      <div className="card empty-state">
        <div className="spinner spinner-dark" style={{ margin: '0 auto 16px' }} />
        <p>Loading ticket #{ticketId}...</p>
      </div>
    );
  }

  if (error && !ticket) {
    return (
      <div className="card">
        <div className="alert alert-error">
          <AlertCircle size={20} />
          <div>{error}</div>
        </div>
        <button onClick={onBack} className="btn btn-secondary">
          <ArrowLeft size={16} />
          <span>Back to Dashboard</span>
        </button>
      </div>
    );
  }

  if (!ticket) return null;

  return (
    <div>
      {/* Top Header & Navigation */}
      <div style={{ marginBottom: '20px' }}>
        <button
          onClick={onBack}
          className="btn btn-secondary btn-sm"
          style={{ marginBottom: '14px' }}
        >
          <ArrowLeft size={15} />
          <span>Back to Dashboard</span>
        </button>

        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', flexWrap: 'wrap', gap: '16px' }}>
          <div>
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '6px' }}>
              <span style={{ fontSize: '0.85rem', fontWeight: 600, color: 'var(--text-muted)' }}>
                TICKET ID: {ticket.id}
              </span>
            </div>
            <h1 className="page-title">{ticket.subject}</h1>
          </div>

          <div style={{ display: 'flex', alignItems: 'center', gap: '8px', flexWrap: 'wrap' }}>
            <StatusBadge status={ticket.status} />
            <UrgencyBadge urgency={ticket.urgency} />
            <CategoryBadge category={ticket.category} />
          </div>
        </div>
      </div>

      {/* Notifications / Feedback */}
      {successToast && (
        <div className="alert alert-success">
          <Check size={18} />
          <span>{successToast}</span>
        </div>
      )}

      {error && (
        <div className="alert alert-error">
          <AlertCircle size={18} />
          <span>{error}</span>
        </div>
      )}

      {/* Main Ticket Grid */}
      <div className="detail-grid">
        {/* Left Column: Complaint & AI Reply */}
        <div className="detail-main">
          {/* AI Executive Summary Card */}
          <div className="card" style={{ borderLeft: '4px solid #c084fc' }}>
            <div className="card-header">
              <div className="card-title" style={{ color: '#7e22ce' }}>
                <Sparkles size={18} />
                <span>AI Executive Summary</span>
              </div>
              <span style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>
                Generated by Gemini API
              </span>
            </div>
            <div className="ai-summary-box">
              {ticket.ai_summary || 'No summary generated.'}
            </div>
          </div>

          {/* Original Customer Complaint */}
          <div className="card">
            <div className="card-header">
              <div className="card-title">
                <MessageSquare size={18} style={{ color: 'var(--primary)' }} />
                <span>Original Customer Complaint</span>
              </div>
            </div>
            <div className="complaint-box">
              {ticket.complaint}
            </div>
          </div>

          {/* AI-Generated Customer Support Reply */}
          <div className="card" style={{ borderLeft: '4px solid #22c55e' }}>
            <div className="card-header">
              <div className="card-title" style={{ color: '#15803d' }}>
                <Bot size={20} />
                <span>AI-Generated Customer Support Response</span>
              </div>
              <div style={{ display: 'flex', gap: '8px' }}>
                <button
                  type="button"
                  onClick={handleCopyReply}
                  className="btn btn-secondary btn-sm"
                  title="Copy reply text"
                >
                  {copied ? <Check size={14} color="#16a34a" /> : <Copy size={14} />}
                  <span>{copied ? 'Copied!' : 'Copy Reply'}</span>
                </button>

                <button
                  type="button"
                  onClick={handleRegenerateReply}
                  disabled={regenerating}
                  className="btn btn-secondary btn-sm"
                  title="Regenerate alternative AI reply"
                >
                  <RefreshCw size={14} className={regenerating ? 'spinner spinner-dark' : ''} />
                  <span>{regenerating ? 'Regenerating...' : 'Regenerate Reply'}</span>
                </button>
              </div>
            </div>

            <div className="ai-reply-box">
              {regenerating ? (
                <div style={{ textAlign: 'center', padding: '24px 0', color: 'var(--text-secondary)' }}>
                  <div className="spinner spinner-dark" style={{ margin: '0 auto 12px' }} />
                  <p>Requesting alternative support resolution from Google Gemini API...</p>
                </div>
              ) : (
                ticket.ai_reply || 'No AI reply generated.'
              )}
            </div>

            <div style={{ marginTop: '12px', fontSize: '0.8rem', color: 'var(--text-muted)', display: 'flex', justifyContent: 'space-between' }}>
              <span>Generated server-side with Google Gemini API</span>
              <span>Last Updated: {formatDate(ticket.updated_at)}</span>
            </div>
          </div>
        </div>

        {/* Right Sidebar: Customer Profile & Status Controls */}
        <div className="detail-sidebar">
          {/* Ticket Status Controller */}
          <div className="card">
            <div className="card-header">
              <div className="card-title">
                <ShieldCheck size={18} style={{ color: 'var(--primary)' }} />
                <span>Ticket Status</span>
              </div>
            </div>

            <p style={{ fontSize: '0.85rem', color: 'var(--text-secondary)', marginBottom: '14px' }}>
              Change the operational lifecycle status of this support request:
            </p>

            <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
              <button
                type="button"
                disabled={updatingStatus || ticket.status === 'Pending'}
                onClick={() => handleStatusChange('Pending')}
                className={`btn ${ticket.status === 'Pending' ? 'btn-primary' : 'btn-secondary'}`}
                style={{
                  justifyContent: 'flex-start',
                  backgroundColor: ticket.status === 'Pending' ? 'var(--status-pending-bg)' : undefined,
                  color: ticket.status === 'Pending' ? 'var(--status-pending-text)' : undefined,
                  borderColor: ticket.status === 'Pending' ? 'var(--status-pending-border)' : undefined,
                }}
              >
                <Clock size={16} />
                <span>Mark as Pending</span>
              </button>

              <button
                type="button"
                disabled={updatingStatus || ticket.status === 'AI Responded'}
                onClick={() => handleStatusChange('AI Responded')}
                className={`btn ${ticket.status === 'AI Responded' ? 'btn-primary' : 'btn-secondary'}`}
                style={{
                  justifyContent: 'flex-start',
                  backgroundColor: ticket.status === 'AI Responded' ? 'var(--status-ai-bg)' : undefined,
                  color: ticket.status === 'AI Responded' ? 'var(--status-ai-text)' : undefined,
                  borderColor: ticket.status === 'AI Responded' ? 'var(--status-ai-border)' : undefined,
                }}
              >
                <Bot size={16} />
                <span>Mark as AI Responded</span>
              </button>

              <button
                type="button"
                disabled={updatingStatus || ticket.status === 'Resolved'}
                onClick={() => handleStatusChange('Resolved')}
                className={`btn ${ticket.status === 'Resolved' ? 'btn-primary' : 'btn-secondary'}`}
                style={{
                  justifyContent: 'flex-start',
                  backgroundColor: ticket.status === 'Resolved' ? 'var(--status-resolved-bg)' : undefined,
                  color: ticket.status === 'Resolved' ? 'var(--status-resolved-text)' : undefined,
                  borderColor: ticket.status === 'Resolved' ? 'var(--status-resolved-border)' : undefined,
                }}
              >
                <Check size={16} />
                <span>Mark as Resolved</span>
              </button>
            </div>
          </div>

          {/* Customer Profile Card */}
          <div className="card">
            <div className="card-header">
              <div className="card-title">
                <User size={18} style={{ color: 'var(--primary)' }} />
                <span>Customer Profile</span>
              </div>
            </div>

            <div style={{ display: 'flex', flexDirection: 'column', gap: '14px' }}>
              <div>
                <span className="metric-label">Name</span>
                <p style={{ fontWeight: 700, fontSize: '1rem', color: 'var(--text-primary)', marginTop: '2px' }}>
                  {ticket.customer_name}
                </p>
              </div>

              <div>
                <span className="metric-label">Email Address</span>
                <div style={{ marginTop: '2px' }}>
                  <a
                    href={`mailto:${ticket.customer_email}`}
                    style={{
                      display: 'inline-flex',
                      alignItems: 'center',
                      gap: '6px',
                      color: 'var(--primary)',
                      fontSize: '0.9rem',
                      fontWeight: 600,
                      textDecoration: 'none',
                    }}
                  >
                    <Mail size={14} />
                    <span>{ticket.customer_email}</span>
                  </a>
                </div>
              </div>

              <div style={{ borderTop: '1px solid var(--border-color)', paddingTop: '12px' }}>
                <span className="metric-label">Date Submitted</span>
                <p style={{ fontSize: '0.85rem', color: 'var(--text-secondary)', marginTop: '2px', display: 'flex', alignItems: 'center', gap: '6px' }}>
                  <Calendar size={14} />
                  <span>{formatDate(ticket.created_at)}</span>
                </p>
              </div>
            </div>
          </div>

          {/* AI Metadata Overview */}
          <div className="card">
            <div className="card-header">
              <div className="card-title">
                <Sparkles size={18} style={{ color: 'var(--primary)' }} />
                <span>Triage Metadata</span>
              </div>
            </div>

            <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
              <div>
                <span className="metric-label">Assigned Category</span>
                <div style={{ marginTop: '4px' }}>
                  <CategoryBadge category={ticket.category} />
                </div>
              </div>

              <div>
                <span className="metric-label">Calculated Urgency</span>
                <div style={{ marginTop: '4px' }}>
                  <UrgencyBadge urgency={ticket.urgency} />
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
